"""award_requests table

Revision ID: c0fccfc8a16c
Revises: e1b17c1088c6
Create Date: 2018-07-05 16:12:15.120333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fccfc8a16c'
down_revision = 'e1b17c1088c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_award', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_request_file_name'), 'award_request', ['file_name'], unique=False)
    op.create_index(op.f('ix_award_request_message'), 'award_request', ['message'], unique=False)
    op.create_index(op.f('ix_award_request_required_award'), 'award_request', ['required_award'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_request_required_award'), table_name='award_request')
    op.drop_index(op.f('ix_award_request_message'), table_name='award_request')
    op.drop_index(op.f('ix_award_request_file_name'), table_name='award_request')
    op.drop_table('award_request')
    # ### end Alembic commands ###
